### ISSUE TITLE
Fabric 1.19.x support please

### ISSUE THREAD

**Issue by ghost** [tr7zw/GraphUtil#2]
![image](https://user-images.githubusercontent.com/75373609/192146320-3b6d9dff-179e-471c-a21b-051bac436669.png)

**Comment by tr7zw** [comment]
You downloaded the 1.18 release.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/192146401-be48cf91-d787-4677-94f3-2c73b49408ed.png)
ah I got screwed over by modrinth again... Will have to reupload all the jars probably so it correctly displays the 1.19 fabric release.

**Comment by ghost** [comment]
Yep, 1.19. is sadly missed on Modrinth. Thanks for the super fast reaction.

**Comment by tr7zw** [comment]
https://modrinth.com/mod/graphutil/versions fixed.
