### ISSUE TITLE
Fabric/Quilt/Forge: The F3 menu graph is not rendered correctly with Minecraft 1.20

### ISSUE THREAD

**Issue by Lolothepro** [tr7zw/GraphUtil#7]
1.19.4:
![2023-06-11_12 11 29](https://github.com/tr7zw/GraphUtil/assets/68275908/11cad66b-5df1-429c-a561-824bd7ad6d3e)
1.20:
![2023-06-11_12 14 01](https://github.com/tr7zw/GraphUtil/assets/68275908/d928f40a-280a-49e6-a238-2a7a95c3d470)

As you can see, the graph with Minecraft 1.20 is darker

**Comment by tr7zw** [comment]
Yea I noticed that, but didnt look further into it. Probably changed the color format or color space for the lines.
